requires:
- name: "toolchain-go"
  category: "development"
  version: ">=0"
prelude:
- mkdir go/src/github.com/${GITHUB_ORG}/ -p
- |
   cd go/src/github.com/${GITHUB_ORG}/ && \
   git clone https://github.com/${GITHUB_ORG}/${GITHUB_REPO}.git
env:
- GOPATH=/luetbuild/go/
- GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
- GITHUB_REPO={{ ( index .Values.labels "github.repo" ) }}
- GIT_HASH={{ ( index .Values.labels "git.hash" ) }}
- CGO_ENABLED=0
steps:
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  cd go/src/github.com/${GITHUB_ORG}/${GITHUB_REPO}/  && \
  git checkout {{.Values.hash}} -b build && go build -ldflags="-w -s -X github.com/mudler/edgevpn/internal.Version=v$PACKAGE_VERSION" && mv $GITHUB_REPO /usr/bin/
- chmod +x /usr/bin/${GITHUB_REPO}
