package_dir: /package
steps:
- apk add git
- git clone --depth 1 https://github.com/armbian/firmware.git
- |
   cd firmware/ && \
   mkdir -p /package/lib/firmware/brcm/ && \
   cp brcm/BCM4345C5.hcd /package/lib/firmware/brcm/BCM4345C5.hcd && \
   cp brcm/brcmfmac43456-sdio.txt /package/lib/firmware/brcm/brcmfmac43456-sdio.pine64,pinebook-pro.txt && \
   cp brcm/brcmfmac43456-sdio.bin /package/lib/firmware/brcm/brcmfmac43456-sdio.bin && \
   cp brcm/brcmfmac43456-sdio.clm_blob /package/lib/firmware/brcm/brcmfmac43456-sdio.clm_blob

image: "alpine"