image: alpine

copy:
- image: "quay.io/luet/base:0.32.5"
  source: "/usr/bin/luet"
  destination: "/usr/bin/luet"

prelude:
- |
   mkdir -p /etc/luet/repos.conf.d && \
   luet repo add --type docker --reference "v{{.Values.version}}-repository.yaml" --yes --url quay.io/costoolkit/releases-teal elemental
package_dir: /framework
steps:
- |
   /usr/bin/luet install -y --system-target /framework \
            meta/cos-light \
            cloud-config/recovery \
            cloud-config/live \
            cloud-config/network \
            cloud-config/boot-assessment \
            cloud-config/rootfs \
            system-openrc/cos-setup
excludes:
- var/cache|var/cache/.*
- usr/bin/elemental