image: alpine
steps:
- mkdir -p /etc/systemd/system
- mkdir -p /etc/dracut.conf.d
- cp -rf tmp.mount /etc/systemd/system
- mkdir -p /usr/lib/dracut/modules.d
- cp -r 30cos-immutable-rootfs /usr/lib/dracut/modules.d
- cp 02-cos-immutable-rootfs.conf /etc/dracut.conf.d
- cp 02-cos-setup-initramfs.conf /etc/dracut.conf.d
- cp 50-cos-initrd.conf /etc/dracut.conf.d
- cp -rfv 30cos-immutable-rootfs/cos-setup-*.service /etc/systemd/system
