{{ if .Values.init  }}
  {{ if eq .Values.init "systemd" }}
image: golang:1.18
prelude:
- apt-get update
- apt-get install -y git
  {{ else }}
image: golang:1.18-alpine
prelude:
- apk add git
  {{ end }}
- git clone https://github.com/kairos-io/provider-kairos
- |
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    cd provider-kairos && git checkout v$PACKAGE_VERSION
steps:
- mkdir -p /system/providers
- cd provider-kairos && go build -o agent-provider-kairos
- mv provider-kairos/agent-provider-kairos /system/providers/agent-provider-kairos
- ln -s /system/providers/agent-provider-kairos /usr/bin/kairos
{{ end }}