image: alpine
prelude:
- apk add git
- git clone https://github.com/kairos-io/kairos
- |
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    cd kairos && git checkout v$PACKAGE_VERSION
steps:
- mkdir -p /system/oem
- cp -rfv kairos/overlay/files/system/oem/* /system/oem
