# This is only for amd64
{{ if .Values.arch }}
  {{ if eq .Values.arch "amd64" }}
image: registry.opensuse.org/opensuse/leap:15.3

prelude:
- zypper ref
steps:
- zypper in -y shim

includes:
- usr/share/efi/.*/*.efi
excludes:
# This is shipped by system/grub2-efi
- usr/share/efi/.*/grub.efi
  {{end}}
{{end}}