image: "{{.Values.image}}"
env:
- DEBIAN_FRONTEND=noninteractive
steps:

{{ if eq .Values.pm "apt-get" }}
- |
  apt update && \
  apt-get install -y {{.Values.packages}} && apt-get clean && rm -rf /var/cache/* 
{{ else if eq .Values.pm "zypper" }}
- |
  zypper ref && \
  zypper in -y {{.Values.packages}} && zypper cc
{{ end }}